steps:
# get dependencies
- name: 'node:alpine'
  args: ['yarn']
# build
- name: 'node:alpine'
  args: ['yarn', 'build']
# dockerize
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
# store docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
# remove old Dockerfile
- name: 'alpine'
  args: ['rm', 'Dockerfile']
# move deploy Dockerfile
- name: 'alpine'
  args: ['mv', 'Dockerfile.deploy', 'Dockerfile']
# rename deploy Dockerfile source
- name: 'alpine'
  args: ['sed', '-i', 's~%IMAGE%~gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA~g', 'Dockerfile']
# store docker image
# images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']