steps:
# get dependencies
# - name: 'gcr.io/cloud-builders/npm'
- name: 'node'
  args: ['yarn', 'install']
# build
# - name: 'gcr.io/cloud-builders/npm'
- name: 'node'
  args: ['yarn',  'build']
# dockerize
# - name: 'gcr.io/cloud-builders/docker'
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd-ui', '.']
# store docker image
images: ['gcr.io/$PROJECT_ID/cicd-ui']