steps:
# get dependencies
- name: 'node:alpine'
  args: ['yarn']
# build
- name: 'node:alpine'
  args: ['yarn',  'build']
# dockerize
- name: 'docker'
  args: ['build', '-t', 'grc.io/$PROJECT_ID/cicd-ui', '.']
# store docker image
images: ['grc.io/$PROJECT_ID/cicd-ui']