steps:
# get dependencies
- name: 'node:alpine'
  args: ['yarn']
# build
- name: 'node:alpine'
  args: ['yarn',  'build']
# dockerize
- name: 'docker'
  args: ['build', '-t', 'grc.io/$PROJECT_ID/ui', '.']
# store docker image
- name: 'docker'
  args: ['push', 'grc.io/$PROJECT_ID/ui']