steps:
# get dependencies
# - name: 'gcr.io/cloud-builders/npm'
- name: 'npm'
  args: ['install']
# build
# - name: 'gcr.io/cloud-builders/npm'
- name: 'npm'
  args: ['run',  'build']
# dockerize
# - name: 'gcr.io/cloud-builders/docker'
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd-ui', '.']
# store docker image
images: ['gcr.io/$PROJECT_ID/cicd-ui']