steps:
# get dependencies
- name: 'node:alpine'
  args: ['yarn']
# build
- name: 'node:alpine'
  args: ['yarn',  'build']
# dockerize
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID-$SHORT_SHA', '.']
# store docker image
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID-$SHORT_SHA']